apiVersion: v1
kind: Service
metadata:
  name: rag
  labels:
    app.kubernetes.io/name: rag
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: rag
  ports:
    - name: http
      port: 8000
      targetPort: http
